version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app  
    restart: always

    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', res => process.exit(res.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"]
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 5

  frontend:
    build: ./frontend/devops-interview
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always