apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: interview-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Oluwakomiyo/My-devops-Interview.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: interview
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
